modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv3"
issueTrackerURL="https://github.com/BlizzardFenix/Weaponized-Baseball-Mod/issues"
showAsResourcePack=false
[[mods]] #mandatory
	modId="webasemod"
	version="${file.jarVersion}"
	displayName="Weaponized Baseball Mod"
	updateJSONURL="https://raw.githubusercontent.com/BlizzardFenix/Weaponized-Baseball-Mod/1.16/UpdateChecker.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/weaponized-baseball-mod"
	logoFile="banner.png"
	#credits=""
	authors="BlizzardFenix"
	description="Introduces baseball and bouncy throwables to Minecraft."
	#displayTest="MATCH_VERSION"

	[[dependencies.webasemod]]
		modId="forge"
		mandatory=true
		versionRange="[40,)"
		ordering="NONE"
		side="BOTH"
	[[dependencies.webasemod]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.18.2,1.19)"
		ordering="NONE"
		side="BOTH"
